### ISSUE TITLE
Test failed:   IndexBaseAndGitRepoJobTest.testDetermineBinary

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#101]
Hi, 

I got  IndexBaseAndGitRepoJobTest.testDetermineBinary:124 expected:<[1]> but was:<[0]> on current version.

from what I understand the size is the number of elements in the list so not sure why you expecting 1 in this code:
```
    public void testDetermineBinary() {
        IndexGitRepoJob gitRepoJob = new IndexGitRepoJob();
        List<String[]> reportList = new ArrayList<>();

        boolean result = gitRepoJob.determineBinary("", "", new ArrayList<>(), reportList);

        assertThat(result).isTrue();
        assertThat(reportList.size()).isEqualTo(1);
    }
```

**Comment by boyter** [comment]
That would be due to this test not actually being isolated, and using the properties file without overriding some of the values. The one in question being "log_indexed" which I am willing to bet is false in your version.

Added the appropriate setup logic to deal with this.

I really should expose the build server for stuff like this so people can see. It did indicate the failure, just I hadn't gotten around to resolving it yet.

Thanks for raising the issue. I would have found it eventually when running the full test suite but its nice to catch earlier.
