### ISSUE TITLE
about search

### ISSUE THREAD

**Issue by zhuzhujulie** [boyter/searchcode-server#119]
Hi
i read this statement below from the index.ftl:
  <form method="GET" class="form-inline" <#if isHtml??>action="/html/"</#if>>  

so, what do you mean "if isHtml??"
if i search something from the index page, obviously that it doesn's from the route:/html/,  so where does it go, which route???

**Comment by boyter** [comment]
Say you have installed searchcode server on your local machine and visit,

http://localhost:8080/

And then perform a search, you will see the Javascript search frontend. If how ever you visit

http://localhost:8080/html/

You will see the pure HTML frontend. That code is just there to know which one it is for links and the like.

**Comment by zhuzhujulie** [comment]
so why do you distinguish these two kinds of implementation.??
a html search fronted and a javascript search fronted.
And do you mean if i search from "http://localhost:8080", i will search by the search_ajax.ftl??

**Comment by zhuzhujulie** [comment]
Or can you tell me where is the javascript that implements the search from "http://localhost:8080/"
Thank you so much~

**Comment by boyter** [comment]
Sorry was away on a break so unable to respond. 

Yes. They are totally different. Its mostly due to how I built things. There isn't a technical reason they are split apart and they may merge at some point in the future.

All the javascript lives in a single file, specifically this one https://github.com/boyter/searchcode-server/blob/master/src/main/resources/public/js/script.js

**Comment by boyter** [comment]
Note there is a bug for the HTML page that was resolved in #120 

If there is nothing else to ask might be worth closing this one down. Will leave it over to you and if no response close in a few days.

**Comment by boyter** [comment]
Going to assume that this is resolved.
