### ISSUE TITLE
Last Index Time not being updated

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#144]
in example:
'''
Indexed ✓ | 220 years ago | 298 | 1437 
'''
but none of my repositories have date different than that. Maybe related to low_memory = true that does not uses Index Lines / Index Queue properties?

**Comment by boyter** [comment]
No its a legitimate bug. I am aware of it just tracking it down :)

**Comment by boyter** [comment]
So there are 3 situations where the repository will have its date set like the above. 

1. When it is first added so it knows to index everything.
2. If you click reindex on the repository index page for a single index.
3. If you restart searchcode server. It makes the assumption that it crashed and rebuilds everything.

Not sure if your case falls into the above. 

I have seen this before but not quite sure how to replicate it. Will continue looking though.

**Comment by quasarea** [comment]
it is case 3, not sure if its wise to reset those on searchcode restart as it looses the track of progress it already made and starts indexing from the beginning. would be much better to have requireReindex flag set on restart and reindex whatever has this flag in last indexing date order.

**Comment by boyter** [comment]
So the reason that it does so is that it has to make the assumption that the previous run failed. Rather than keep track of where it was upto its actually just as fast to reprocess unless it occurs on the first process.

The way it works is like this,

1. Repository is added with a previous run time in the past (200 years).
2. The process walks the file tree indexing any file that has a modified date newer than the previous run time.
3. It then updates the previous run time to the start of the index run.

The reason for a full reprocess when restarting is because as a once off operation it ensures that the entire index is back in sync. Keep in mind that while is is reindexing everything the index being updated is the current readable one, so everything should still work.

Previously it used to use some files that were written into the repository indicating that everything worked but in reality this was less reliable. I am still in the process of evaluating this though while everything is in test so it may change.

**Comment by boyter** [comment]
So I suspect that with the fix was implemented for #149 that this may be resolved for you. I am trying it out on a live install with 200 repositories and it looks promising so far.

@quasarea if you have a chance to try the latest build from master let me know if this resolves it for you.

**Comment by quasarea** [comment]
It seems better now, constant indexing could be an issue there. Even with this away, I have problems with telling:
* which are currently being indexed
* which are waiting in a queue
would be great to see "Queued - 1" like first in queue to be indexed
When indexing is done new date it applied to last index time
![2017-09-19 10_37_23-repository list](https://user-images.githubusercontent.com/10334982/30586329-88cd9b92-9d27-11e7-96bf-9f89bd6727db.png)

**Comment by boyter** [comment]
Those sound like reasonable suggestions. I will have a look at improving the notice of what is going on for these situations and we can see how it goes.

Let me know if the issue reoccurs though. I will be watching my current install to observe how it reacts.

**Comment by boyter** [comment]
Added some better indication of what is going on.

<img width="1192" alt="screen shot 2017-09-20 at 8 41 48 am" src="https://user-images.githubusercontent.com/612151/30618841-94e08e4a-9ddf-11e7-9941-7be5fb1fbd25.png">

**Comment by boyter** [comment]
Sitting in master. Feel free to try it out and let me know how it goes for you.

**Comment by boyter** [comment]
Able to replicate this at last. Will look into the root cause and resolve it.

**Comment by boyter** [comment]
Pretty confident that ea0e0c7843fe950cf4662c6256f5ca8f3c730ee0 will resolve this. 

Root case was that the EnqueueRepositoryJob had a param set that reset the times when starting for the first time. However due to a bug the value was "semi" persisted when running. Anyway moved the value into the singleton which should resolve this for good. 

Have confirmed locally, and will confirm on the test I am using but pretty confident about it. Build from master to confirm if you want.

**Comment by boyter** [comment]
Confirmed that this is now resolved on my long running internal test @quasarea let me know if you encounter this issue again. Otherwise going to move to done and close.

**Comment by quasarea** [comment]
Much better, thanks :) I miss number in a queue but maybe it is just me ;p

**Comment by boyter** [comment]
No that is indeed not there. Something to consider adding at a later date. For the moment this should do though.
