### ISSUE TITLE
Literal Search

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#152]
There seem to be some issue with literal search (the functionality is great tho!)
* http://localhost:8080/?q=fn%3Aassembly* - works fine
* http://localhost:8080/?q=fn%3Aassembly*vb - works fine
* http://localhost:8080/?q=fn%3Aassembly*.vb - no results - seems like . breaks the word into two
* http://localhost:8080/?q=fn%3A*vb - no results - thats already mentioned in help but a bit sad as I cannot filter on extension only :(

**Comment by boyter** [comment]
So as you mentioned you cannot do fn:*vb because of the way the lucene index works.

As for your other example fn:assembly*.vb you can replace the . with _ which should resolve it for you. Anything not in the range a-Z0-9 is replaced with _ when searching against the literal index. This is something I may look to improve in the future but should work for the moment.

**Comment by quasarea** [comment]
Lovely, thanks

**Comment by jingjinjingjin** [comment]
![1](https://user-images.githubusercontent.com/10020402/54881917-f3dabf80-4e8f-11e9-8cae-86c4fef0dd39.PNG)
![2](https://user-images.githubusercontent.com/10020402/54881920-f89f7380-4e8f-11e9-9349-069f03180b7f.PNG)
Issue: Literal search not work
version: 1.3.14 (searchcode server community edition )
I have checked option of literal search.
Please help.
