### ISSUE TITLE
Dashboard - Running Index Jobs

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#153]
Would be great to have this bit redesigned, now it covers all **System Actions** in my case.

You could:
* merge **Words in Spelling Corrector** into **Memory Usage** i.e and extend **Running Index Jobs** to take two rows. It would still require making it scrollbar as it far bigger than two rows when you have 20 indexers running.
* move it under the left hand menu (you could place **Data Values** in its current place)
* additionally seconds could be abbreviated to just s to save some space

**Comment by boyter** [comment]
Yep something that is likely to get fixed in the next few versions. I want to revisit a lot of how the admin screen works.

**Comment by boyter** [comment]
Pretty simple. So implemented. Sitting in master.

**Comment by quasarea** [comment]
I think it looks better that way:
```
        .panel {
            height:200px !important;
            overflow: auto;
        }
```

**Comment by boyter** [comment]
Agree with the first, not so sure about the second. I don't want to put too much information or time into this running box because its only purpose it to let you know if processes are running and if they are taking a long time.

I will keep playing a bit though. Improving the admin screens is something I revisit every now and then.

**Comment by quasarea** [comment]
to defend the second:
* you already are throwing html there `<small>` 
* all other panels have content arranged as lists, just this one is space separated

If I would do it in c# it would be like:
            ```
var result = string.Join("<BR>", Singleton.getRunningIndexRepoJobs()
                .Where(job => job !=null)
                .Select(job => $"{job.Name}  <small>({Singleton.GetHelpers.GetCurrentTimeSeconds() - job.StartTime}s)</small>"));

            return result;
```

or if you have to use string builder:

```
            var stringBuffer = new StringBuilder();
            var jobs = Singleton.getRunningIndexRepoJobs();
            foreach (var job in jobs)
            {
                if (job == null) continue;

                var runningTime = Singleton.GetHelpers.GetCurrentTimeSeconds() - job.StartTime;

                var isLast = job == jobs.Last();

                stringBuffer.Append(job.Name).Append(" <small>(").Append(runningTime).Append("s)</small>").Append(isLast ? "" : "<BR>");
            }

            return stringBuffer.ToString();
```

I don't know why in that place you:
* add a space if job is null, 
* add `&nbsp;` at the end

**Comment by boyter** [comment]
The &nbsp; is there because intercooler.js will not update if there is an empty or whitespace string, which is annoying. I cannot remember the reason for the space though. Probably formatting issues would be my guess.

BTW its possible to achieve the same code almost using Java 8 streams. Its not quite as nice looking at C# but does the job.

```
String collect = Singleton.getRunningIndexRepoJobs().keySet().stream()
                        .filter(x -> Singleton.getRunningIndexRepoJobs().get(x) != null)
                        .map(x -> x + " <small>(" + (Singleton.getHelpers().getCurrentTimeSeconds() - Singleton.getRunningIndexRepoJobs().get(x).startTime) + "s)</small>")
                        .collect(Collectors.joining("<br>"));
```

The result of the above is that it looks like the attached.

<img width="968" alt="screen shot 2017-09-26 at 8 35 52 am" src="https://user-images.githubusercontent.com/612151/30834358-247ee1e0-a296-11e7-880e-e3c7e1da078e.png">

Still not convinced that this is a better outcome though. I had hoped that users would use the superior repository overview page to get this information.

**Comment by quasarea** [comment]
Thats because you have repo names short, in my case those are avg of 42 characters and the longest is 65. I'm using namespaces as repo names.

**Comment by boyter** [comment]
Fair point. The only catch is that is useful for yourself but not for those with short file names.

Anyway irrelevant. I merged it in anyway so its sitting in master.
