### ISSUE TITLE
Indexed instead of Queued on service restart

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#157]
Regarding #144 there is one case I dislike. In example:

![2017-09-25 11_14_22-repository list](https://user-images.githubusercontent.com/10334982/30804494-8dd92814-a1e5-11e7-8c55-881f5b34650c.png)

It looks like that A & B were indexed already before restart while its not true at all. Not sure why those are not in Queued state.

**Comment by boyter** [comment]
So as you noticed this only happens if you restart the server. The reason it says it was indexed is because it was at some point previously indexed and marked as such in the database. Not sure why your file count is 0 but regardless that should clear up the moment it finishes indexing again. The moment that happens the last index time will be updated and everything should be back to normal.

Its a very edge case that should only happen occasionally if you restart the server.

Are you doing this frequently for some reason beyond trying to replicate issues?

**Comment by quasarea** [comment]
nope, you may be right its not worth it ;)
