### ISSUE TITLE
SearchcodeLib.classifier as static

### ISSUE THREAD

**Issue by Ruzzz** [boyter/searchcode-server#19]
1) Now its recreate in IndexBaseRepoJob.indexDocsByPath
2) Full fileName (name.ext) support in lang detection
3) Maybe use Bayesian classifier?

See https://github.com/Ruzzz/searchcode-server/tree/lang_detector

**Comment by boyter** [comment]
I agree. This looks like a worthy change.

I am not sure about the bayesian classification though. It would depend on how it performs in the worst case because if this takes time it will slow down the whole indexing process. So long as it can classify any file faster than 0.1 seconds it should be acceptable as it would only fall back to this logic if it finds a duplicate file extension.

**Comment by boyter** [comment]
This has been moved out. Need to look at using Bayesian classifier for working out the type though.
