### ISSUE TITLE
Problem with checking last version

### ISSUE THREAD

**Issue by yogeek** [boyter/searchcode-server#204]
First, thank you for the great project !

I tested what I thought to be the last version with [this docker image ](https://cloud.docker.com/repository/docker/yogeek/searchcode-server-community) (I forked @arkii one to fix the build error and set up automatic build like I mentionned in the previous issue #203) and in the Admin page > System Statistics panel, I see this :
`Version: 1.3.11 (check if latest version)`
but when I click on the 'check if latest version' link, here is the message displayed :
```
Version: 1.3.11 Your searchcode server version 1.3.11 instance is out of date. The latest version is 1.3.10.
```

Weird isn't it ? ;)

And when I check the version of the demo server (http://demo.searchcodeserver.com/api/v1/version/), the version is `1.3.14`

Does the https://searchcode.com/static/searchcode-server-community.tar.gz release is intended to automatically point to the latest release ?

Thank you !

**Comment by boyter** [comment]
Glad to hear it. Makes all the time working on it worth it.

So what happened is that it used to check against searchcode.com and then I upgraded it to check against searchcodeserver.com because it made more sense and was easier to update. This was done back in 1.13.13 and checks the following URL now https://searchcodeserver.com/version.json

To be fair the check logic there is a little iffy. Its one of those things I need to improve. It just string compares so its possible if you build from source that your version is ahead and it says the same thing.

The current plan is to finish off everything required to get this deployed on searchcode.com as the new codebase, then run through and fix all these annoying issues.

**Comment by yogeek** [comment]
@boyter Ok for the version check. But I did not build from source. I only downloaded the release at https://searchcode.com/static/searchcode-server-community.tar.gz but this archive contains the `searchcode-1.3.11.jar` and not the latest version available. 
So I would like to know where I can download the latest release version in order to keep my docker image up-to-date.
Thanks !

**Comment by yogeek** [comment]
great ! Thank you again :+1:

**Comment by boyter** [comment]
Going to close this down. Will ensure documentation and docker is up-to date at some point in the future.
