### ISSUE TITLE
Please support SHA256 

### ISSUE THREAD

**Issue by opt9** [boyter/searchcode-server#33]
AFAIK, Searchcode-server supports only SHA1

https://github.com/boyter/searchcode-server/blob/bbbc9ffc26207e9346ec437614ce850731753f97/src/main/java/com/searchcode/app/service/ApiService.java#L52

Because of security reason, many vendors start to drop SHA1.
If we can use SHA256, SHA512, etc. it'll be very helpful. ;-)

**Comment by boyter** [comment]
That's a pretty reasonable request. I have been needing to version the API anyway so this is probably as good a reason as any to do so. Its also one of those areas I need to add more tests for as well.

Just out of curiosity though, are you running this as a front end and ran into this issue or where you just looking though the source code?

**Comment by boyter** [comment]
Going to only add SHA512. I don't see the point of supporting SHA256 for this case.

**Comment by boyter** [comment]
Added on the following two commits,

https://github.com/boyter/searchcode-server/commit/35e2dc1dfe861ba83639d40324322c97a20f57fb
https://github.com/boyter/searchcode-server/commit/3e411ce7d7a8115e7825750bffbc1d9f649ad77e

TODO:

- Create ApiRouteService tests to verify logic
- Update API tests to check logic
- Update documentation to reflect change

**Comment by boyter** [comment]
See https://github.com/boyter/searchcode-server/blob/master/assets/integration_test/signed_testing_sha512.py for an example of how to use this.

**Comment by boyter** [comment]
This is now done. If you require this you would have to build your own copy from the master branch from this commit https://github.com/boyter/searchcode-server/commit/fde0c6ed4eed4b687ce6d2e733d2c1d528b49210 which should be stable but has not passed all the usual checks. Keep in mind that it would be under the terms of the fair source licence and limited to 5 user.

Otherwise wait for the next community release, or if you really need it in a hurry you can buy the full version with support at https://searchcode.com/product/ and I can expedite a build for you.

Thanks for raising this. It forced me to add the long overdue unit tests for the API logic which were really needed.

**Comment by opt9** [comment]
Thank you for quick reply and your efforts. ;-)

I'm using 1.3.4 community release.
When you release 1.3.5 community version, I'll update and test drive it.

Thank you.

**Comment by boyter** [comment]
@opt9 This is now live. You can get the latest community edition here https://searchcode.com/product/#downloadlinks

**Comment by opt9** [comment]
Thank you ;-)

**Comment by boyter** [comment]
No problem at all.
