### ISSUE TITLE
Cannot change Syntax Highlighter

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#58]
I'm trying to set up searchode 1.3.7 and I noticed that I cannot change Syntax Highlighter in admin settings, it is always reverting to github after save. Also there is no option in searchcode.properties to update it.

**Comment by zhuzhujulie** [comment]
i want to consult you a simple question, 
I've just implemented the searhcode community version on my computer
And i want to index come repositories, but what's the password at the admin page?
i can find it on the documentation.

**Comment by boyter** [comment]
@quasarea That's due to the the settings page being locked for the community edition. There are two ways to get around this. 

1. Purchase a copy of searchcode server at https://searchcode.com/product/
2. Modify the source code and change the flag which enables community edition. Keep in mind that doing so means you must work within the confines of the Fair Source licences https://github.com/boyter/searchcode-server/blob/master/LICENSE.txt

@zhuzhujulie You have asked this in another issue https://github.com/boyter/searchcode-server/issues/59 but I will answer here as well. The default password is Adm1n234 which can currently be configured by the searchcode.properties file.
