### ISSUE TITLE
search against file name

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#72]
Hi, noticed that if searching for a filename it is not prioritizing such results, maybe it would be worth of scoring matches in filenames/paths higher, so we get class file first and all the references to it below? 

It is slightly better when used filename with extension, but then you are not getting references, especially with languages like c, where you have separated header and implementation.

**Comment by boyter** [comment]
So it actually does match on the filename for all results, however as you say its not a high priority.

It is something that should be fixed though. Will ensure it gets into the next release.

**Comment by boyter** [comment]
This is now sitting in master. Rather than adjust the weights the same process that applies to the content is applied to the filename. This not only boots the filename matches but it the same partial matching will work on filenames as well.

My random testing of a few repositories showed this to be working as expected.

**Comment by boyter** [comment]
NB you will need to reindex for this to work. This is a recommended thing to do with any upgrade though.
