### ISSUE TITLE
Running Jobs more information

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#77]
Hi, 

Wonder why you defaulted running jobs number to 2/2/1 - would be great to have some reasoning in documentation.

I mostly work with file repos and tried 5 for a while already and it seemed fine, today I bumped up value (as I have plenty of small repos) to 20, just to see performance impact (didn't notice it yet) but noticed that only 10 are scanning according to Running Jobs list at the bottom of admin page.

**Comment by boyter** [comment]
To be honest, no real reason other then setting the value too high can cause system thrashing. It really depends on what sort of resources you have available.

I have noticed that searchcode when there is enough data to index becomes bottlenecked by this https://github.com/boyter/searchcode-server/issues/34 but this only happens at about 2,000 documents a second so I have not looked into removing it yet.

The reason you are only seeing 10 running is because you are hitting the limit of threads inside the Quartz scheduler. I should probably investigate making this set to whatever the sum of the job numbers are plus a few extra for the background tasks.

Keep in mind though, that if you do raise the limits on linux you will need to raise the system or user ulimit as well as you will quickly run into the too many files open issue.

TODO: Raise thread count of Quartz.

**Comment by boyter** [comment]
So raising this value is pretty simple. 

Create a quartz.properties file where searchcode is running from and put the following inside,

```org.quartz.threadPool.threadCount=20```

This will raise the number of threads that can run to 20. You can put any positive number upto 100 in here.

**Comment by quasarea** [comment]
Lovely, thanks

**Comment by boyter** [comment]
Have added documentation for this and the number of threads running is now displayed on the admin page. Going to close this down.
