### ISSUE TITLE
Displaying a file using URL

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#82]
Just wonder if its possible, i.e. I search for something and get back result URL like:

`http://localhost:8080/file/d034eced9835fcf28a28dbe3215b131b284cc38e/searchcode/src/main/java/com/searchcode/app/config/IDatabaseConfig.java`

I open result, and while reading I see I need to switch to other file, IData.java i.e. (this more applies to header and implementation files of c++). It would be great to navigate there i.e. just by alternating URL to 

`http://localhost:8080/file/d034eced9835fcf28a28dbe3215b131b284cc38e/searchcode/src/main/java/com/searchcode/app/config/IData.java`

Currently it is impossible due to the d034eced9835fcf28a28dbe3215b131b284cc38e that is different for the other file. so I wonder if its possible to get rid of this part?

Thanks
J

**Comment by boyter** [comment]
So the d034eced9835fcf28a28dbe3215b131b284cc38e is the primary key that drives everything. For background knowledge it is actually a SHA1 hash of the files location on disk. 

The reason for this is that searchcode internally needs a unique key that allows it to look up the file somehow. It serves a few purposes, the main being when you navigate like your example so it knows the details of where to lookup and for knowing which index entry to update/delete and the like. I did have this set to the index id a while ago but since that changes on index updates it is not a good choice. I did try using the file path but this turned out to be problematic and I started running into edge cases with lucene being unable to find the file in question through the lookup. It may be possible to remove it by calculating the hash on the fly but of course this would require you get the case and the like 100% correct.

That said what you are trying to do isn't a bad idea. On searchcode.com I have a way to do this where you can click "View File Tree" which would display all the files in the repository. Maybe just at a file level would be enough in this case. What I would really like though is to go the source-graph route and have smarter linking inside searchcode itself, but this would require having to parse the code itself. Its something I am looking at though.

**Comment by quasarea** [comment]
Thanks, View File Tree looks really useful too, it is not available in community edition?

**Comment by boyter** [comment]
It's not available at all actually. I have not had the time to backport it in. It is something I want to put in and a requirement before moving searchcode.com over to using it. No idea on timelines though.

**Comment by boyter** [comment]
Huh... seems I already implemented this without closing this down :)

You can view it here http://demo.searchcodeserver.com/file/d2aacfe945c65480a0c80adde1d3940f0c66791d/searchcode-server/src/main/resources/spark/template/freemarker/coderesult.ftl and then click on "View File Tree"
