### ISSUE TITLE
pause indexing button missing from admin pages

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#84]
In past I used 'pause indexing' button in order to shut down service in a bit polite way.

Now it seems that the only way is to kill the process while indexing ?

**Comment by boyter** [comment]
Will add the button back now. However this whole section needs to be rewritten as it is not very nice. Hence the removal. There is already a ticket for that https://github.com/boyter/searchcode-server/issues/41

**Comment by boyter** [comment]
Added back in using this 7eb75d48b301dda840a9a66017e4aaf015365ed1

If you really need this you can still turn if off in version 1.3.8 by posting to the following endpoint, which so long as you are logged in will pause the indexing http://localhost:8080/admin/togglepause/

Otherwise build from source and you should be back to where you were.
