### ISSUE TITLE
search results not displayed at all in internet explorer

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#91]
Yep, I have people around who use IE.

Other functions are working correctly, but searching yields nearly empty page.

I opened 'view source' that allows to switch emulation mode (default 7) if I change it to 10 or above it works fine. Below it bring back errors:

* 5,7:
```
SCRIPT5009: 'JSON' is undefined
script.min.js (77,324)
```
* 8
```
SCRIPT438: Object doesn't support property or method 'forEach'
script.min.js (79,194)
```
* 9
No errors, just not display results
* 10,11 works fine

this maybe useful:
http://stackoverflow.com/questions/17627851/how-to-force-compatibility-mode-for-all-versions-of-ie

**Comment by boyter** [comment]
Sorry but I am not going to support internet explorer 9 or below, simply because of the increased development cost to do so. I will have a quick look at IE9 and if it is simple to fix it I will implement but there is no chance I will be looking to do so for IE8 and below.

For the moment thought the best option at this point would be to have them use the HTML only version of searchcode http://localhost:8080/html/ or to upgrade the browser.

Sorry about that, but adding the effort to support these very old browsers means that there would be considerably less time to add new functionality.

**Comment by quasarea** [comment]
I got this on IE11, I think you have to add some meta that states that IE has to run in higher version emulation mode, as 7 is default

http://stackoverflow.com/questions/22842463/how-to-set-ie11-default-emulating-core

**Comment by boyter** [comment]
I do have the <!DOCTYPE html> added at the top of each of the pages... I will have a quick look tonight about this but for the moment can you have those unable to use Chrome/Firefox/Safari please use HTML mode. Although I have to ask why you have developers being forced to use IE at all.

**Comment by quasarea** [comment]
unfortunately that is their choice, so it is much harder to change than enforced rule :)

**Comment by boyter** [comment]
A dev that prefers IE? Never thought I would see the day.

**Comment by quasarea** [comment]
I found it astonishing as well. I think we exhausted the subject and hopefully your fix will do the magic for those one.
